### ISSUE TITLE
Add custom testStubOutputDirectory 

### ISSUE THREAD

**Issue by brempusz** [kaczynskid/spring-io-lab12#1]
By default IDEA will classes generated from groovy tests to generated sources - it will cause compilation errors. To fix it custom `testStubOutputDirectory` can be configured:

```
			<plugin>
				<groupId>org.codehaus.gmavenplus</groupId>
				<artifactId>gmavenplus-plugin</artifactId>
				<version>1.5</version>
				<configuration>
					<testStubsOutputDirectory>${project.build.directory}/generated-test-sources/groovy-stubs/test</testStubsOutputDirectory>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>addTestSources</goal>
							<goal>testGenerateStubs</goal>
							<goal>testCompile</goal>
							<goal>removeTestStubs</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by brempusz** [comment]
Releated issue in GMavenPlus: https://github.com/groovy/GMavenPlus/issues/52

**Comment by kaczynskid** [comment]
This in turn makes Idea mark that directory as test sources that duplicates code from `src/test/groovy` and beaks project compilation. I don't the location where the stubs are generated, but don't want them to break my IDE build.
